name: ssvep_analysis_toolbox
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.4
  - scipy
  - pip
  - py7zr
  - pooch
  - joblib
  - matplotlib
  - tqdm
  - pip:
    - mat73